### ISSUE TITLE
Do I have your permission to use it in my project?

### ISSUE THREAD

**Issue by takasurazeem** [askvasim/CustomChipView#1]
https://github.com/takasurazeem/QuranMajeed/commit/6051249aec25c7f3b3e339565486204fc77d5b54

**Comment by takasurazeem** [comment]
Sorry, I could not figure out the way to set a fixed height for this and hence, will have to use this one instead: https://github.com/FiveStarsBlog/CodeSamples/tree/main/Flexible-SwiftUI

**Comment by askvasim** [comment]
Hi,

Sorry for the late response, Yes you can use this in your project or modify
as per your need.

Also I do not get what issue you are facing, Let me know and I'll try my
best to help you with the issue.

Regards,
Waseem Khan
